# keeps computed results in dirs
debug: True

# true -> work with pbs on metacentrum
# false -> run locally, no pbs
run_on_metacentrum: False

# number of samples
n_samples: 1
task_size: 0.001
collect_only: False
mesh_only: False

copy_files: [config.yaml, flow_mc_new.py, 01_hm_tmpl.yaml]

# The flow executable and arguments to use.
local:
  flow_executable:
  #  - /home/jb/workspace/flow123d_JB/bin/fterm
    - /home/paulie/Workspace/flow123d/bin/fterm
    - --no-term
    - rel
    - run
  np: 1
  gmsh_executable:
    - /home/paulie/Workspace/Endorse-2Dtest/venv/bin/gmsh

metacentrum:
  flow_executable:
  # release
    #- /storage/liberec3-tul/home/jan_brezina/workspace/flow123d/bin/flow123d
    #- '/storage/liberec3-tul/home/pavel_exner/workspace/flow123d/build-PE_wgc2020/bin/mpiexec'
    #- '-np'
    #- '10'
    - '/storage/liberec3-tul/home/pavel_exner/workspace/flow123d/build-PE_wgc2020/bin/flow123d'
  # debug
  #- /storage/liberec3-tul/home/jan_brezina/workspace/flow-dbg/flow123d/bin/flow123d
  gmsh_executable:
    #- /storage/liberec3-tul/home/martin_spetlik/astra/gmsh/bin/gmsh
    - /storage/liberec3-tul/home/pavel_exner/WGC2020-THM-MC/wgc2020_model/env/bin/gmsh


end_time: &end_time 365
output_times: &output_times
  - {begin: 0, step: 1, end: 20}
  - {begin: 20, step: 2, end: 30}
  - {begin: 30, step: 5, end: *end_time}

geometry:
  # depth of the center of the box and of the coordinate system
#  center_depth: 5000
  # x,y,z dimension
  box_dimensions: [100, 100]
  # tunnel center
  tunnel_center: [0, 0, 0]
  tunnel_dimX: &tunnel_dimX 4.375 # X cross-section
  tunnel_dimY: &tunnel_dimY 3.5 # X cross-section
  tunnel_mesh_step: 0.5

# base of the mesh file name
mesh_name: random_fractures

# parameters substituted into the HM model template
hm_params:
    # The mesh to use in both simulations.
    #mesh: three_frac_symmetric.msh
    mesh: random_fractures.msh # healed mesh is used at the end (programmatically replaced)
    in_file: 01_hm

    output_times: *output_times
    end_time: *end_time

    tunnel_dimX: *tunnel_dimX
    tunnel_dimY: *tunnel_dimY

    bulk_conductivity: &bulk_cond_init 6e-15  #6e-15
    # K = k * rho * g /mu
    # permeability k=6e-22 m2
    # dynamic viscosity mu=0.001 Pa.s

    mechanics_solver__a_tol: 1e-14
    mechanics_solver__r_tol: 1e-7
        # -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg
    mechanics_solver__options: -ksp_type cg -pc_type icc -pc_factor_levels 2 -ksp_diagonal_scale -ksp_diagonal_scale_fix -pc_factor_fill 3.0 -ksp_monitor


    flow_solver__a_tol: &fatol   1e-14
    flow_solver__r_tol: &frtol   1e-7
        # Boomeramg options:
        # -ksp_type richardson              - recomended usage when solving just by multigrid
        #  -pc_hypre_boomeramg_cycle_type <V> Cycle type (choose one of) V W (None)
        #                                 cans try: V, W
        #  -pc_hypre_boomeramg_max_levels <25>: Number of levels (of grids) allowed (None)
        #  -pc_hypre_boomeramg_max_iter <1>: Maximum iterations used PER hypre call (None)
        #                                  PETSC recomend more then 1 when just richardson KSP is used
        #  -pc_hypre_boomeramg_tol <0.>: Convergence tolerance PER hypre call (0.0 = use a fixed number of iterations) (None)
        #                                  PETSC says 1e-7 is default, when previous is not set
        #  -pc_hypre_boomeramg_strong_threshold <0.25>: Threshold for being strongly connected (None)
        #                                  HYPRE recommends 0.5 for 3d problems
        #
        #  -pc_hypre_boomeramg_P_max <0>: Max elements per row for interpolation operator (0=unlimited) (None)
        #  -pc_hypre_boomeramg_agg_nl <0>: Number of levels of aggressive coarsening (None)
        #  -pc_hypre_boomeramg_agg_num_paths <1>: Number of paths for aggressive coarsening (None)
        #  -pc_hypre_boomeramg_strong_threshold <0.25>: Threshold for being strongly connected (None)
        #  -pc_hypre_boomeramg_coarsen_type <Falgout> Coarsen type (choose one of) CLJP Ruge-Stueben  modifiedRuge-Stueben   Falgout  PMIS  HMIS (None)
        #  -pc_hypre_boomeramg_interp_type <classical> Interpolation type (choose one of) classical   direct multipass multipass-wts ext+i ext+i-cc standard standard-wts block block-wtd FF FF1 (None)

        #  -pc_hypre_boomeramg_relax_type_all <symmetric-SOR/Jacobi> Relax type for the up and down cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
        #  -pc_hypre_boomeramg_relax_type_down <symmetric-SOR/Jacobi> Relax type for the down cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
        #  -pc_hypre_boomeramg_relax_type_up <symmetric-SOR/Jacobi> Relax type for the up cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
        #  -pc_hypre_boomeramg_relax_type_coarse <Gaussian-elimination> Relax type on coarse grid (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
        #  -pc_hypre_boomeramg_relax_weight_all <1.>: Relaxation weight for all levels (0 = hypre estimates, -k = determined with k CG steps) (None)
        #  -pc_hypre_boomeramg_relax_weight_level <1.>: Set the relaxation weight for a particular level (weight,level) (None)
        #  -pc_hypre_boomeramg_outer_relax_weight_all <1.>: Outer relaxation weight for all levels (-k = determined with k CG steps) (None)
        #  -pc_hypre_boomeramg_outer_relax_weight_level <1.>: Set the outer relaxation weight for a particular level (weight,level) (None)
        #  -pc_hypre_boomeramg_no_CF: <FALSE> Do not use CF-relaxation (None)


        # -pc_hypre_boomeramg_max_iter <1>  - number of V/W cycles
        # -pc_hypre_boomeramg_tol <1e-7>    - tolerance of MG solver
        # -pc_hypre_boomeramg_coarsen_type  [PMIS  HMIS]  - recomenden for 3d problems
        # -pc_hypre_boomeramg_interp_type [ext+i ext+i-cc] - probably recomended for 3d problems
        # -pc_hypre_boomeramg_strong_threshold <0.5> - recomended for 3d problems
        # for cg one must use symmetric smoother (default is hybrid Gauss-Siedel)
        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg

        # Experiements:
        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg
        # it: 421 r_tol 1e-7
        #options: -ksp_type gmres -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5 -ksp_monitor
        # it: 696 r_tol 1e-7
        #options: -ksp_type gmres -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type HMIS -pc_hypre_boomeramg_strong_threshold 0.5 -ksp_monitor
        # it: 705 r_tol 1e-7
        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor
        # it: 414 r_tol 1e-7
        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor -pc_hypre_boomeramg_relax_type_all FCF-Jacobi
        # failed: indefinite PC
        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor -pc_hypre_boomeramg_relax_type_all Jacobi
        # failed: indefinite PC
        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor -pc_hypre_boomeramg_relax_type_all Chebyshev

    flow_solver__options: &fopt -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type HMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor
        # it: 414 r_tol 1e-7

        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor -pc_hypre_boomeramg_relax_type_all symmetric-SOR/Jacobi
        #options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor -pc_hypre_boomeramg_relax_type_all Jacobi

        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_interp_type ext+i -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor
        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_interp_type ext+i -pc_hypre_boomeramg_strong_threshold 0.4  -ksp_monitor
        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_interp_type ext+i -pc_hypre_boomeramg_strong_threshold 0.6  -ksp_monitor